apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "skypilot-k8s-labeler.fullname" . }}-gpu-labeler-sa
  namespace: {{ .Values.namespace }}
  labels:
    parent: {{ .Values.parent }}
    job: {{ include "skypilot-k8s-labeler.fullname" . }}-gpu-labeler